# databases:
#   - name: mysite
#     databaseName: mysite
#     user: mysite

# services:
#   - type: web
#     name: mysite
#     env: ruby
#     # buildCommand: "./bin/render-build.sh"
#     buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
#     # startCommand: "bundle exec puma -C config/puma.rb"
#     startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
#     plan: free # optional (defaults to starter)
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mysite
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false

services:
  - name: my-blog-site
    plan: free # optional (defaults to starter)
    type: web
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-blog-db
          property: connectionString

databases:
  - name: my-blog-db
    plan: free # optional (defaults to starter)
    ipAllowList: [] # only allow connections from services in this Render account